default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("DATABASE_USER", "test_app") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "test_password") %>

development:
  <<: *default
  database: test_app_development

test:
  <<: *default
  database: test_app_test

production:
  <<: *default
  database: test_app_production
